[33mWARNING [0m juju.client.connection:connection.py:861 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:762 Adding model github-pr-d7e0d-lxd:test-ha-b477 on cloud localhost
[33mWARNING [0m juju.client.connection:connection.py:861 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:861 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:861 unexpected facade SSHTunneler received from the controller
[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:haproxy-0
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [allocating] waiting: agent initialising
[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/noble/hacluster-139
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [idle] active: 
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [idle] blocked: 1 validation error for HAInformation
  Value error, vip needs to be configured in ha mode. [type=value_error, input_value=ArgsKwargs((), {'ha_integ...'configured_vip': None}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [idle] blocked: 1 validation error for HAInformation
  Value error, vip needs to be configured in ha mode. [type=value_error, input_value=ArgsKwargs((), {'ha_integ...'configured_vip': None}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error
  hacluster/0 [idle] active: Unit is ready and clustered
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  haproxy/0 [idle] active: 
  hacluster/0 [idle] active: Unit is ready and clustered
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model         Controller           Cloud/Region         Version  SLA          Timestamp
test-ha-b477  github-pr-d7e0d-lxd  localhost/localhost  3.6.11   unsupported  01:04:40Z

App        Version  Status  Scale  Charm      Channel   Rev  Exposed  Message
hacluster  2.1.6    active      1  hacluster  2.4/edge  139  no       Unit is ready and clustered
haproxy             active      1  haproxy                0  no       

Unit            Workload  Agent  Machine  Public address  Ports   Message
haproxy/0*      active    idle   0        10.146.117.54   80/tcp  
  hacluster/0*  active    idle            10.146.117.54           Unit is ready and clustered

Machine  State    Address        Inst id        Base          AZ             Message
0        started  10.146.117.54  juju-09d4d7-0  ubuntu@24.04  github-runner  Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

machine-0: 01:00:55 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:00:55 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-haproxy-0: 01:03:32 ERROR unit.haproxy/0.juju-log ha:2: Error setting up charm state.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-haproxy-0/charm/src/state/ha.py", line 78, in from_charm
    return cls(
           ^^^^
  File "/var/lib/juju/agents/unit-haproxy-0/charm/venv/pydantic/_internal/_dataclasses.py", line 121, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for HAInformation
  Value error, vip needs to be configured in ha mode. [type=value_error, input_value=ArgsKwargs((), {'ha_integ...'configured_vip': None}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-haproxy-0/charm/src/state/validation.py", line 63, in wrapper
    return method(instance, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-haproxy-0/charm/./src/charm.py", line 200, in _on_config_changed
    self._reconcile()
  File "/var/lib/juju/agents/unit-haproxy-0/charm/./src/charm.py", line 255, in _reconcile
    ha_information = HAInformation.from_charm(self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-haproxy-0/charm/src/state/ha.py", line 85, in from_charm
    raise HAInformationValidationError(str(exc)) from exc
state.ha.HAInformationValidationError: 1 validation error for HAInformation
  Value error, vip needs to be configured in ha mode. [type=value_error, input_value=ArgsKwargs((), {'ha_integ...'configured_vip': None}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...